categories:
  - title: '🚀 Features'
    label: 'Feature 🎁'
  - title: '💣 Breaking Change'
    label: 'Breaking Change 💣'
  - title: '🐛 Bug Fixes'
    label: 'Bug 🐛'
  - title: '📝 Documentation'
    label: 'Documentation 📝'
  - title: '🔨 Maintenance'
    label: 'Maintenance 🔨'
tag-template: 'some tag template $version'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
template: |
  ## Getting Vanilla Framework

  Install with NPM: https://www.npmjs.com/package/vanilla-framework
  Visit the documentation at https://vanillaframework.io/docs
  
  v: $RELEASE_VERSION
  n: $RELEASE_NAME
  t: $RELEASE_TAG

  ## New in Vanilla $RELEASE_VERSION

  $CHANGES
