name: Vanilla framework - Examples

baseurl: /vanilla-framework

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

plugins:
  - jekyll-redirect-from

# Keep Jekyll directories out of the way
plugins_dir:  _jekyll/_plugins
includes_dir:  _jekyll/_includes
layouts_dir:  _jekyll/_layouts
destination: _jekyll/_site

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [
    "*.md", "*.scss", "node_modules", "package.json",
    "Gemfile", "Gemfile.lock", "gulpfile.js", "gulp",
    "LICENSE", "run", 'vendor/bundle', "yarn.lock", "docs"
]

