const path = require('path');
const sass = require('sass');

const compileSettingsProbe = () =>
  sass.compileString(
    `
      @import 'settings';

      .typography-settings-probe {
        h1: #{map-get($settings-text-h1, font-size)}rem map-get($settings-text-h1, line-height) map-get($settings-text-h1, nudge) map-get($settings-text-h1, sp-after);
        h1-mobile: #{map-get($settings-text-h1-mobile, font-size)}rem map-get($settings-text-h1-mobile, line-height) map-get($settings-text-h1-mobile, nudge) map-get($settings-text-h1-mobile, sp-after);
        h2: #{map-get($settings-text-h2, font-size)}rem map-get($settings-text-h2, line-height) map-get($settings-text-h2, nudge) map-get($settings-text-h2, sp-after);
        h2-mobile: #{map-get($settings-text-h2-mobile, font-size)}rem map-get($settings-text-h2-mobile, line-height) map-get($settings-text-h2-mobile, nudge) map-get($settings-text-h2-mobile, sp-after);
        h3: #{map-get($settings-text-h3, font-size)}rem map-get($settings-text-h3, line-height) map-get($settings-text-h3, nudge) map-get($settings-text-h3, sp-after);
        h4: #{map-get($settings-text-h4, font-size)}rem map-get($settings-text-h4, line-height) map-get($settings-text-h4, nudge) map-get($settings-text-h4, sp-after);
        h5: #{map-get($settings-text-h5, font-size)}rem map-get($settings-text-h5, line-height) map-get($settings-text-h5, nudge) map-get($settings-text-h5, sp-after);
        h6: #{map-get($settings-text-h6, font-size)}rem map-get($settings-text-h6, line-height) map-get($settings-text-h6, nudge) map-get($settings-text-h6, sp-after);
        p: #{map-get($settings-text-p, font-size)}rem map-get($settings-text-p, line-height) map-get($settings-text-p, nudge) map-get($settings-text-p, sp-after);
        display: #{map-get($settings-text-display, font-size)}rem map-get($settings-text-display, line-height) map-get($settings-text-display, nudge) map-get($settings-text-display, sp-after);
        display-mobile: #{map-get($settings-text-display-mobile, font-size)}rem map-get($settings-text-display-mobile, line-height) map-get($settings-text-display-mobile, nudge) map-get($settings-text-display-mobile, sp-after);
        small: #{map-get($settings-text-small, font-size)}rem map-get($settings-text-small, line-height) map-get($settings-text-small, nudge) map-get($settings-text-small, sp-after);
        x-small: #{map-get($settings-text-x-small, font-size)}rem map-get($settings-text-x-small, line-height) map-get($settings-text-x-small, nudge) map-get($settings-text-x-small, sp-after);
      }
    `,
    {
      loadPaths: [path.join(__dirname, '..', 'scss')],
      silenceDeprecations: ['global-builtin', 'import'],
    },
  ).css;

// font-size / line-height / nudge / sp-after, as generated by the baseline nudge generator.
test('Headings use the Canonical type scale', () => {
  expect(compileSettingsProbe()).toMatchInlineSnapshot(`
    ".typography-settings-probe {
      h1: 2.625rem 3rem 0.56881rem 1.5rem;
      h1-mobile: 2rem 2.5rem 0.53875rem 1.5rem;
      h2: 2.625rem 3rem 0.56881rem 1.5rem;
      h2-mobile: 2rem 2.5rem 0.53875rem 1.5rem;
      h3: 1.5rem 2rem 0.46917rem 1.5rem;
      h4: 1.5rem 2rem 0.46917rem 1.5rem;
      h5: 1rem 1.5rem 0.41rem 1.5rem;
      h6: 1rem 1.5rem 0.41rem 1.5rem;
      p: 1rem 1.5rem 0.41rem 1.5rem;
      display: 5.25rem 6rem 0.1644rem 1.5rem;
      display-mobile: 4rem 4.5rem 0.34313rem 1.5rem;
      small: 0.875rem 1.25rem 0.0775rem 1rem;
      x-small: 0.75rem 1rem 0.245rem 1rem;
    }"
  `);
});

// Vanilla derives margin-bottom as sp-after - nudge, so an element occupies
// line-height + sp-after. That total must be a whole number of baseline units.
// `small` is excluded: its 2.5-unit line-height and 2-unit sp-after give 4.5,
// which predates this scale and is left alone here.
test('Every level occupies a whole number of baseline units', () => {
  const css = sass.compileString(
    `
      @use 'sass:math';
      @import 'settings';

      .baseline-units-probe {
        @each $level in ($settings-text-h1, $settings-text-h1-mobile, $settings-text-h2, $settings-text-h2-mobile, $settings-text-h3, $settings-text-h4, $settings-text-h5, $settings-text-h6, $settings-text-p, $settings-text-display, $settings-text-display-mobile, $settings-text-x-small) {
          units: math.div(map-get($level, line-height) + map-get($level, sp-after), $sp-unit);
        }
      }
    `,
    {
      loadPaths: [path.join(__dirname, '..', 'scss')],
      silenceDeprecations: ['global-builtin', 'import'],
    },
  ).css;

  const units = [...css.matchAll(/units: ([\d.]+)/g)].map((match) => Number(match[1]));

  expect(units).toHaveLength(12);
  units.forEach((value) => expect(Number.isInteger(value)).toBe(true));
});

// A whole-unit line-height keeps every line of a wrapped block on the grid.
// `small` is the documented exception: 14px text takes 20px of leading, which is
// 2.5 units, so it sits on the 0.25rem sub-grid and only re-syncs every second line.
// Nothing else may opt into that.
test('Only small text uses a half-unit line-height', () => {
  const css = sass.compileString(
    `
      @use 'sass:math';
      @import 'settings';

      .line-height-units-probe {
        @each $level in ($settings-text-h1, $settings-text-h1-mobile, $settings-text-h2, $settings-text-h2-mobile, $settings-text-h3, $settings-text-h4, $settings-text-h5, $settings-text-h6, $settings-text-p, $settings-text-display, $settings-text-display-mobile, $settings-text-x-small) {
          units: math.div(map-get($level, line-height), $sp-unit);
        }
        small-units: math.div(map-get($settings-text-small, line-height), $sp-unit);
      }
    `,
    {
      loadPaths: [path.join(__dirname, '..', 'scss')],
      silenceDeprecations: ['global-builtin', 'import'],
    },
  ).css;

  const units = [...css.matchAll(/ units: ([\d.]+)/g)].map((match) => Number(match[1]));
  const smallUnits = Number(css.match(/small-units: ([\d.]+)/)[1]);

  expect(units).toHaveLength(12);
  units.forEach((value) => expect(Number.isInteger(value)).toBe(true));
  expect(smallUnits).toBe(2.5);
});
