name: Vanilla framework documentation

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

plugins:
  - jekyll-redirect-from

exclude: ['nginx.conf', 'redirects.map', 'Dockerfile']
