#! /usr/bin/env bash

set -e

RUN_COMMAND="talisker.gunicorn webapp.app:app --bind $1 --worker-class sync --workers 5 --name talisker-`hostname` --access-logfile -"

if [ "${FLASK_DEBUG}" = true ] || [ "${FLASK_DEBUG}" = 1 ]; then
    echo ""
    echo "= Running talisker with development settings ="
    echo ""
    RUN_COMMAND="${RUN_COMMAND} --reload --log-level debug --timeout 9999"
fi

${RUN_COMMAND}

