# WIP, this is so far a copy of the c.com config
# https://github.com/canonical/canonical.com/pull/1746
name: Deploy

on:
  push:
    branches:
      - main
      # TODO remove these after PR is merged - they are just for testing
      - feature/charm
      - feature/charm-rock
  release:
    types:
      - published

env:
  CHARMCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: true
  ROCKCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: true
  CHARM_NAME: vanillaframework-io-charm

jobs:
  pack-rock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Build Assets
        run: |
          yarn install
          yarn run build

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Create repositories directory
        run: |
          mkdir -m 777 repositories
          mkdir -m 777 tree-cache

      - name: Setup Rockcraft
        run: sudo snap install rockcraft --classic --channel=latest/edge

      - name: Pack Rock
        run: rockcraft pack

      - name: Upload Rock
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CHARM_NAME }}
          path: ./*.rock

  publish-image:
    runs-on: ubuntu-latest
    needs: pack-rock
    outputs:
      image_url: ${{ steps.set_image_url.outputs.image_url }}
    steps:
      - name: Get Rock
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.CHARM_NAME }}

      - name: Set image URL
        id: set_image_url
        run: echo "image_url=ghcr.io/canonical/vanilla-framework:$(date +%s)-${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Push to GHCR
        run: skopeo --insecure-policy copy oci-archive:$(ls *.rock) docker://${{ steps.set_image_url.outputs.image_url }} --dest-creds "canonical:${{ secrets.GITHUB_TOKEN }}"