name: Release Drafter

on:
  push:
    branches:
      - main
  # temporary to allow testing the release drafter action
  pull_request:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # Only need package.json as it is used by the get_version step to pass tag number into release-drafter
          sparse-checkout: package.json

      - name: Get version number from package.json
        id: get_version
        run: |
          set -e
          echo "::set-output name=version_number::$(jq -r '.version' package.json)"

      - name: Draft release notes
        uses: release-drafter/release-drafter@v6
        with:
          # Setting tag and name override the name-template and tag-template.
          # See https://github.com/release-drafter/release-drafter?tab=readme-ov-file#action-inputs for more
         tag: v${{ steps.get_version.outputs.version_number }}
         name: v${{ steps.get_version.outputs.version_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
